feat: add tutti appunti
csunibo/informatica-teorica pull request #5
Opened 2024-05-26 20:40 UTC by Flecart

Ho aggiunto i miei appunti personali.
Secondo me potrebbero fare comodo ad alcuni, dovrei averli scritti bene.

L'unico problema forse è il formato non è totalmetne compatibile!?

2024-05-26 20:58 UTC, foxyseta requested changes
Puoi sistemare i nomi in modo automatizzato usando qualcosa tipo `stdrename -krD .`. La build invece fallisce perché i nomi hanno gli spazi, che ora sistemo lato config direi.

I link interni potrebbero dare problemi. Le tag <img> in stile html forse pure. Sistemo la CI/CD e vediamo.

2024-05-29 20:26 UTC, samuelemusiani commented
@Flecart @foxyseta ora la build funziona, bisogna risolvere i nomi dei file e si può mergiare :)

2024-05-29 20:54 UTC, foxyseta commented
> @Flecart @foxyseta ora la build funziona, bisogna risolvere i nomi dei file e si può mergiare :)

grandissimo :)

2024-06-02 20:35 UTC, foxyseta approved these changes

2024-06-02 20:35 UTC, merged